#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyExpenses.Android.Resource", IsApplication=true)]

namespace MyExpenses.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::MyExpenses.Android.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::MyExpenses.Android.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::MyExpenses.Android.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::MyExpenses.Android.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::MyExpenses.Android.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::MyExpenses.Android.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::MyExpenses.Android.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::MyExpenses.Android.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::MyExpenses.Android.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::MyExpenses.Android.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::MyExpenses.Android.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::MyExpenses.Android.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::MyExpenses.Android.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::MyExpenses.Android.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::MyExpenses.Android.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::MyExpenses.Android.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::MyExpenses.Android.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::MyExpenses.Android.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::MyExpenses.Android.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::MyExpenses.Android.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::MyExpenses.Android.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::MyExpenses.Android.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::MyExpenses.Android.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::MyExpenses.Android.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::MyExpenses.Android.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::MyExpenses.Android.Resource.Styleable.ProgressWheel_ahTextSize;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::MyExpenses.Android.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::MyExpenses.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int pop = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int standard_padding = 2131099648;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_new = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_content_save = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_refresh = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_errorstatus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_launcher = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_successstatus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int monoandroidsplash = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int roundedbg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int roundedbgdark = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090009
			public const int billable = 2131296265;
			
			// aapt resource value: 0x7f09000b
			public const int category = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int date = 2131296268;
			
			// aapt resource value: 0x7f090001
			public const int due = 2131296257;
			
			// aapt resource value: 0x7f090005
			public const int loadingImage = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int loadingProgressBar = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int loadingProgressWheel = 2131296262;
			
			// aapt resource value: 0x7f090011
			public const int menu_new_expense = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int menu_refresh = 2131296274;
			
			// aapt resource value: 0x7f090010
			public const int menu_save_expense = 2131296272;
			
			// aapt resource value: 0x7f090000
			public const int name = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int notes = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int progressBar = 2131296271;
			
			// aapt resource value: 0x7f090007
			public const int textView1 = 2131296263;
			
			// aapt resource value: 0x7f09000d
			public const int textView2 = 2131296269;
			
			// aapt resource value: 0x7f09000a
			public const int textView3 = 2131296266;
			
			// aapt resource value: 0x7f090008
			public const int textView4 = 2131296264;
			
			// aapt resource value: 0x7f090004
			public const int textViewStatus = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int total = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int item_expense = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingprogress = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int view_expense = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int view_expenses = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu_expense = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int menu_expenses = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menu_new_expense = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int menu_refresh = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int menu_save_expense = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Mono_Android_Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
